#!/usr/bin/env tsx
/**
 * Phase 6: regenerate the exp-7-style findings table from any run's log.
 *
 * Findings docs become generated, not hand-written:
 *
 *   npm run report:turns -- logs/<session>.jsonl
 *   npm run report:turns            # newest logs/*.jsonl
 *
 * Reads the `turn_telemetry` events the orchestrator logs per turn and
 * prints the summary + per-turn + per-stage tables (see
 * src/core/telemetry.ts). Exits 2 when the log has no telemetry events
 * (e.g. a pre-Phase-6 log).
 */

import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import {
  formatFindingsReport,
  turnTelemetryFromLogLines,
} from "../src/core/telemetry.js";

function newestJsonl(dir: string): string | undefined {
  let best: { path: string; mtime: number } | undefined;
  let files: string[];
  try {
    files = readdirSync(dir);
  } catch {
    return undefined;
  }
  for (const f of files) {
    if (!f.endsWith(".jsonl")) continue;
    const path = join(dir, f);
    let mtime = 0;
    try {
      mtime = statSync(path).mtimeMs;
    } catch {
      continue;
    }
    if (best === undefined || mtime > best.mtime) best = { path, mtime };
  }
  return best?.path;
}

const arg = process.argv[2];
const logPath = arg ?? newestJsonl("logs");
if (logPath === undefined) {
  console.error("report:turns: no log file given and no logs/*.jsonl found.");
  console.error("usage: npm run report:turns -- logs/<session>.jsonl");
  process.exit(2);
}

let raw: string;
try {
  raw = readFileSync(logPath, "utf-8");
} catch (err) {
  console.error(`report:turns: cannot read ${logPath}: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(2);
}

const turns = turnTelemetryFromLogLines(raw.split("\n"));
if (turns.length === 0) {
  console.error(
    `report:turns: no turn_telemetry events in ${logPath} — ` +
      "this log predates the Phase-6 build (or no turns completed).",
  );
  process.exit(2);
}

console.log(`# Turn economics — ${logPath}`);
console.log("# (generated by `npm run report:turns`; do not hand-edit)");
console.log("");
console.log(formatFindingsReport(turns));
